Novo Layout
LinkNacional/whmcs-orderforms-standard_cart pull request #4
Opened 2024-09-13 19:12 UTC by Abraao2005

2024-10-16 18:35 UTC, GuilhermeLinkNacional requested changes
- [x] Validar data de nascimento caso ela seja enviada
- [ ] Se possivel em caso de erros no formulário, guardar também o endereço para que o usuário não precise digitar novamente, como está sendo feito nos outros campos
- [ ] Diferenciar cor do texto com a cor do placeholder dos campos
- [x] Somente fazer a mascara no CPF quando o usuario fizer o onchange no input e desfazer quando o usario focar no input, pois não está apagando caracteres especiais do campo
- [ ] Corrigir label de estado

2024-10-17 19:33 UTC, GuilhermeLinkNacional requested changes
Acredito que apenas falte adicionar um limite de caracteres e não permitir que o usuário escreva letras em campos que só devem aceitar números:

![image](https://github.com/user-attachments/assets/62a1d8d0-5ecd-4004-8ee3-10a1cf9776fa)
![image](https://github.com/user-attachments/assets/4f562608-9433-4ed9-a841-df9d08f2e5e2)
![image](https://github.com/user-attachments/assets/37c355b6-0c19-4103-8426-c6471a33012f)

2024-10-18 16:30 UTC, Abraao2005 commented
> Acredito que apenas falte adicionar um limite de caracteres e não permitir que o usuário escreva letras em campos que só devem aceitar números:
> 
> ![image](https://private-user-images.githubusercontent.com/161341491/377607843-62a1d8d0-5ecd-4004-8ee3-10a1cf9776fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjg3NTgsIm5iZiI6MTcyOTI2ODQ1OCwicGF0aCI6Ii8xNjEzNDE0OTEvMzc3NjA3ODQzLTYyYTFkOGQwLTVlY2QtNDAwNC04ZWUzLTEwYTFjZjk3NzZmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxNjIwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDNlN2Q3YTJkY2UzMTg4YWIyYmYwZTVlODU3ODUzMmY0OWZhMGIyMjEwZWQ4MGUwZWEyMjQ1OTQ1ZjY1YzEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2wXu2iFbS_HvLYaqAd2OqP1WIM_kLvTkhMqyy8RRvik) ![image](https://private-user-images.githubusercontent.com/161341491/377607995-4f562608-9433-4ed9-a841-df9d08f2e5e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjg3NTgsIm5iZiI6MTcyOTI2ODQ1OCwicGF0aCI6Ii8xNjEzNDE0OTEvMzc3NjA3OTk1LTRmNTYyNjA4LTk0MzMtNGVkOS1hODQxLWRmOWQwOGYyZTVlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxNjIwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWUxNTJmMzRiNmQyNjk5YzgyOGJmMjY4NGNmNDA5YTJkMDc2ZjJmNmIwZDI5MzhiZWMwYjczYTlkYjk4MzE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9FhdJJ4Z2lSGqe8sYSoAWrMoSVBJC4d2TMJw3B1ZVjQ) ![image](https://private-user-images.githubusercontent.com/161341491/377608427-37c355b6-0c19-4103-8426-c6471a33012f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjg3NTgsIm5iZiI6MTcyOTI2ODQ1OCwicGF0aCI6Ii8xNjEzNDE0OTEvMzc3NjA4NDI3LTM3YzM1NWI2LTBjMTktNDEwMy04NDI2LWM2NDcxYTMzMDEyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxNjIwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzJiNWQ5Y2I1OThmYzAwN2RiNWU1ZjIxYjAwYmUzOTQ3ZDRhYWNhNzBhZTI3N2JhYTllMGFiYTRiMzJjOTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.R7l6AckEM7WEyJRPM22rUOvkbvRF8tOjlO6yvM2UHj8)



> Acredito que apenas falte adicionar um limite de caracteres e não permitir que o usuário escreva letras em campos que só devem aceitar números:
> 
> ![image](https://private-user-images.githubusercontent.com/161341491/377607843-62a1d8d0-5ecd-4004-8ee3-10a1cf9776fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjkyNTgsIm5iZiI6MTcyOTI2ODk1OCwicGF0aCI6Ii8xNjEzNDE0OTEvMzc3NjA3ODQzLTYyYTFkOGQwLTVlY2QtNDAwNC04ZWUzLTEwYTFjZjk3NzZmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxNjI5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzdlMmM2NmQxYWEyZDA4MjU5YzNmZjM0ZjM5MTQzNWI1Yjk1MmFkYzM5YmYwNWNjMDFlZTU0NjVjOGY4MjEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VzMyv1VlDDdoQOuuNs-3vZp_gR_94BeYB71ri9EZeyQ) ![image](https://private-user-images.githubusercontent.com/161341491/377607995-4f562608-9433-4ed9-a841-df9d08f2e5e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjkyNTgsIm5iZiI6MTcyOTI2ODk1OCwicGF0aCI6Ii8xNjEzNDE0OTEvMzc3NjA3OTk1LTRmNTYyNjA4LTk0MzMtNGVkOS1hODQxLWRmOWQwOGYyZTVlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxNjI5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDVhZThiMzlmZTBiNzg0OWNjZTQxMTJlZTkwNWZhZjBjOGMxOTQ3MTllNmQ0OTMwYmE1ZGM2N2EyYjAwMTIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GcuAZuaW9lZemWnnG6ym1x8potjIbHD9mnR7gUaJmhk) ![image](https://private-user-images.githubusercontent.com/161341491/377608427-37c355b6-0c19-4103-8426-c6471a33012f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjkyNTgsIm5iZiI6MTcyOTI2ODk1OCwicGF0aCI6Ii8xNjEzNDE0OTEvMzc3NjA4NDI3LTM3YzM1NWI2LTBjMTktNDEwMy04NDI2LWM2NDcxYTMzMDEyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxNjI5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmFiMDk2NDBiOTFkNmY0ZTRiNTZhYmEzODcxNGU3N2FjNTE5YjA1NGM5M2RmZWZhYzJkODEwNzJjZDUyMjUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bnPV-HSDJDv5MS1uuTDh1qMWx9_Px8KtbhXpzIaJf30)


No caso desses problemas, não vai ser possivel a alteração, por exemplo: No Código postal tem paises que tem letras também, CPF se ficar com o campo number ele não consegue fazer a formatação e o telefone do mesmo jeito do CPF ele não formata quando fica no number

2024-10-22 14:21 UTC, GuilhermeLinkNacional approved these changes

2024-11-18 19:42 UTC, Abraao2005 commented
@emanuellopess PR completo!

2024-11-22 11:26 UTC, merged